homebrew:
  - name: gitteams
    description: GitTeams gives you insight into multiple repositories at once.
    homepage: https://github.com/NoUseFreak/gitteams
    url: https://github.com/NoUseFreak/gitteams/releases/download/{{ .Version }}/darwin_amd64.zip
    version: "{{ .Version }}"
    tap:
      url: git@github.com:NoUseFreak/homebrew-brew.git
    test: system "#{bin}/{{ .Name }} -h"