letitgo:
  name: letitgo
  description: LetItGo automates releases.
  actions:
    - type: changelog

    - type: archive
      source: "./build/bin/*"
      target: "./build/pkg/"
      extras:
        - "LICENSE"
        - "CHANGELOG.md"

    - type: githubrelease
      assets:
      - ./build/pkg/*

    - type: homebrew
      homepage: https://github.com/NoUseFreak/letitgo
      url: https://github.com/NoUseFreak/letitgo/releases/download/{{ .Version }}/darwin_amd64.zip
      tap:
        url: git@github.com:NoUseFreak/homebrew-brew.git
      test: system "#{bin}/{{ .Name }} -h"

    - type: gofish
      githubusername: NoUseFreak
      homepage: https://github.com/NoUseFreak/letitgo
      artifacts:
        - os: darwin
          arch: amd64
          url: https://github.com/NoUseFreak/letitgo/releases/download/{{ .Version }}/darwin_amd64.zip
        - os: linux
          arch: amd64
          url: https://github.com/NoUseFreak/letitgo/releases/download/{{ .Version }}/linux_amd64.zip
        - os: windows
          arch: amd64
          url: https://github.com/NoUseFreak/letitgo/releases/download/{{ .Version }}/windows_amd64.zip

    - type: slack
      channel: "#released"
 