language: go
go:
- stable
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/release.sh
  on:
    repo: NoUseFreak/letitgo
    branch: master
    tags: true
env:
  global:
    secure: eXU8LpBG3MVGFrln0lf/Me/JgOIpxy9m14OHLSeHZgCZOkRlzMIulBhqliOM/7jydZZ9IO7ESRVi37SLlOK6ohRDgmJ6sbYm7NEnnoiaG6+fJ5ZhJ9niramDpOF4BSEXLBbWS6ZTGNrpHLIWdgHlcJVzlsbpc/V2ITAHJLiMPVSisdfUFVHcEdx7Ak58o2CYow8RVPFRTEGd20ZDl0ZlLP29sj+BlcrqHuaC/0DKttBO5s16nYf75e4Hg5sK4yFnq456gp8sVJHjBm9AoYVThDtulhAAK/U0k5CL8fzsfJViWFLkPJbqe08+jtoQkG8RPC7OK7Y5KJOM2sgEoJT+ujRV7V9aB6tpNwdpM9sPOrnnvvSy+2KzwmBSnUYzkHcAvkBxVtD9xu3flb74ajHvpqFDP+IG0j9njAIJ6RRm6+EZzF+vmv541UITQJJxz1ylBoh2AsKNnV7FZ9NCgDND+0RpPz2gl5m5nyTdkuo4IJcVsqjAdO608iRC0DnKlWDNu5eV04XC/n/HfTOl3FpTsth3/p4l/5LT3ncH3BCoruqk63VePwiZMhPVnP/xtnezDl2JjZiEObxAIuc4E9GdM/FIWjLrht6OcrCdF1cBeBXpg4t6JAsIkv5lyitINJErZckak2jBaLCQEbDkMSLWb/vE3n8mARDRI67yYI3vqxs=
